### ISSUE TITLE
Feature: Automation of issue management and pull requests using Actions.

### ISSUE THREAD

**Issue by prjctimg** [prjctimg/huetiful#84]
>  Is there a way we can automate some of these tasks as well ? Such as GitHub Actions?

Yeah we can automate assigning issues with github actions, like we do on [open-sauced](https://github.com/open-sauced). i.e -> https://github.com/open-sauced/app/issues/1988

![2023-11-08_10-04](https://github.com/prjctimg/huetiful/assets/79809121/6cd032c8-8713-4588-9b1f-bac62c23a941)

Here is the workflow file -> https://github.com/open-sauced/hot/blob/beta/.github/workflows/triage.yml

_Originally posted by @takanome-dev in https://github.com/prjctimg/huetiful/discussions/62#discussioncomment-7508491_

**Comment by prjctimg** [comment]
What should we consider when making a workflow for this type of scenario. I have no experience with GitHub Actions and they confuse me a bit

@takanome-dev

**Comment by takanome-dev** [comment]
> What should we consider when making a workflow for this type of scenario.

I don't quite understand what you mean, but if we want to give contributors the ability to assign to issues themselves we should consider adding the [take-action](https://github.com/bdougie/take-action?tab=readme-ov-file#example-workflow). Otherwise, we can assign them manually if they want to work on particular issue.

Not sure if that answer your question, please let me know

**Comment by prjctimg** [comment]
> > What should we consider when making a workflow for this type of scenario.
> 
> I don't quite understand what you mean, but if we want to give contributors the ability to assign to issues themselves we should consider adding the [take-action](https://github.com/bdougie/take-action?tab=readme-ov-file#example-workflow). Otherwise, we can assign them manually if they want to work on particular issue.
> 
> Not sure if that answer your question, please let me know



That sounds great! I think we should automate as many aspects of the project as we can. That's what I meant and also an action for welcoming contributors who open a new issue.



Would you please help set it up ? I'll fill in the required auth tokens in the workflow in your pull request.


Please let me know the best way forward!

**Comment by takanome-dev** [comment]
@prjctimg can you help me here

I saw a lot of prs merged into main but the last once was the branch dev merged into main. Since you merged it, I assume there were not (or you fixed) conflicts. I'm confused by the screenshot below

![2023-11-10_07-38](https://github.com/prjctimg/huetiful/assets/79809121/332aad31-4988-4228-bc2e-e758aeebc8ed)

Normally, I should be able to pull latest changes from main but this looks like there were changes in main and those changes were not in the dev branch.

I'm confused :sweat_smile: Please enlighten me :pray:

**Comment by prjctimg** [comment]
😅 Git is a bit tricky for me. I think its because I orphaned my dev branch, created a common ancestor commit then did a few force pushes on the main branch. 


The easiest way to resynchronize the branches would be to do a force pull and just accept the incoming changes (if they don't affect your working tree).


I'll be more careful with my commits in the future!


Have you solved it yet?

**Comment by takanome-dev** [comment]
> Have you solved it yet?

Yeah, but got an error after installing the deps.

| | |
| ------ | ------ |
| ![ts-err-1](https://github.com/prjctimg/huetiful/assets/79809121/3084f0b1-70ca-41fa-9a5d-26a84db8e6df) | ![ts-err-2](https://github.com/prjctimg/huetiful/assets/79809121/bc00f6ae-bbbd-4580-ba9e-5c6e6c0e40f5) |

Note sure what's going but it's not a blocker for this issue though

**Comment by prjctimg** [comment]
> > Have you solved it yet?
> 
> Yeah, but got an error after installing the deps.
> 
> ![ts-err-1](https://user-images.githubusercontent.com/79809121/282171116-3084f0b1-70ca-41fa-9a5d-26a84db8e6df.png)	![ts-err-2](https://user-images.githubusercontent.com/79809121/282171163-bc00f6ae-bbbd-4580-ba9e-5c6e6c0e40f5.png)
> Note sure what's going but it's not a blocker for this issue though

@takanome-dev 

That bug has been patched a few commits ago on the dev branch. Will open a pull request a few hours from now with the patches. 


We're deploying a patch on NPM as well this Sunday. Will keep you updated 👍
